# Generated by Django 5.0.2 on 2024-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
