# Generated by Django 5.0.2 on 2024-05-24 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_question_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField()),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='icon',
        ),
        migrations.AddField(
            model_name='question',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technologeis', to='Quiz.technologies'),
            preserve_default=False,
        ),
    ]
