# Generated by Django 5.0.2 on 2024-05-24 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0010_purchase_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custo_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchased_by', to='courses.course'),
        ),
    ]
