# Generated by Django 5.0.2 on 2024-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_custo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default=1, upload_to='accounts/profile/pctiure/'),
            preserve_default=False,
        ),
    ]
