# Generated by Django 5.0.2 on 2024-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Content/Video'),
        ),
    ]
