# Generated by Django 5.0.2 on 2024-03-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_asked_questions_benefits_community_our_partners_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asked_Questions',
            new_name='AskedQuestions',
        ),
        migrations.RenameModel(
            old_name='Our_partners',
            new_name='Ourpartners',
        ),
    ]
