# Generated by Django 5.0.2 on 2024-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_asked_questions_askedquestions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedquestions',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='askedquestions',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='askedquestions',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='askedquestions',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='askedquestions',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='askedquestions',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='title_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
