# Generated by Django 5.0.2 on 2024-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='images',
            field=models.ImageField(blank=True, upload_to='courses/banners/'),
        ),
    ]
