# Generated by Django 5.0.2 on 2024-05-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_accesscode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessCode',
        ),
    ]
