# Generated by Django 5.0.2 on 2024-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_content_is_unlocked_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='courses.module'),
        ),
    ]
